### ISSUE TITLE
[Refactor] 메서드 분리 리팩토링

### ISSUE THREAD

**Issue by geniusYoo** [morib-in/Morib-Server-v2#23]
## 📍 Issue
리뷰를 반영해 메서드를 분리 리팩토링을 진행합니다.

<br>

## ✏️  Todo
- [ ] HomeViewFacade `fetch()` VO 구성 및 코드 리팩토링
- [x] Dto build 클래스 분리
- [x] CategoryManager `classifyTaskByCategory` 메서드 분리
