### ISSUE TITLE
[Fix] conflict 해결 중 빠진 부분 fix 및 추가적으로 발견된 리팩토링 작업 진행합니다.

### ISSUE THREAD

**Issue by khyojun** [morib-in/Morib-Server-v2#47]
## 📍 Issue
conflict 해결 중 빠진 부분 fix 및 추가적으로 발견된 리팩토링 작업 진행합니다.

<br>

## ✏️  Todo
- [x] conflict 해결 중 빠진 부분 관련하여 수정 작업 진행
- [x] createTodoService 제대로 구현되지 못한 부분 수정
- [x] 반환타입, import문 사용되지 않는 부분 수정
- [x] conflict로 인해 기능이 겹친 중복된 메서드 삭제 작업 진행
