### ISSUE TITLE
[Feat] 배포를 위한 세팅 작업들 진행 

### ISSUE THREAD

**Issue by khyojun** [morib-in/Morib-Server-v2#60]
## 📍 Issue
배포를 위한 작업들을 진행합니다! 코드 상에 들어난 작업, 인프라 작업들이 있습니다.
<br>

## ✏️  Todo
- [x] Dockerfile 작성
- [x] aws 세팅 후 도메인 적용
   - [x] nginx 적용
   - [x] mysql, application network 설정 -> 묶어서 진행
   - [x] https, route53 작업 진행 (현재 이슈 FE 싱크하고 진행해야 할 거 같음!)

**Comment by khyojun** [comment]
![image](https://github.com/user-attachments/assets/55008482-477f-421f-a66f-34668930b713)

테스트 url 바탕으로 작업 완료하였습니다!

**Comment by geniusYoo** [comment]
확인했습니다 :) 고생하셨습니다!!!
