### ISSUE TITLE
[Refactor] 기획 수정에 따른 카테고리 도메인 수정

### ISSUE THREAD

**Issue by geniusYoo** [morib-in/Morib-Server-v2#62]
## 📍 Issue
기획 방향 수정에 따라 카테고리는 기간을 갖지 않도록 수정합니다.
<br>

## ✏️  Todo
- [x] startDate, endDate는 현재처럼 유지하되, 둘다 nullable로 설정한 뒤 null로 설정
- [x] 홈뷰 조회 api : 기간 필터링 코드 삭제
- [x] 카테고리 생성 api : 기간 입력되는 dto, 로직 수정
